"""
Django settings for sabrositoDjango project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h#qr!y8nibrwpd7l&gp9j1c&mo5ejt$6ab=se9&=cbtba$*syc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sabrocito.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'paypal.standard.ipn',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sabrositoDjango.User',
    'sabrositoDjango.Cart',
    'sabrositoDjango.Pay',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sabrositoDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

            #Path.joinpath(BASE_DIR, 'sabrosito-react/build)'
            Path.joinpath(BASE_DIR, 'sabrosito-react/templates'),

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sabrositoDjango.Cart.context_processor.total_carrito',
            ],
        },
    },
]

WSGI_APPLICATION = 'sabrositoDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sabrocito$Sabrocito',
        'USER': 'sabrocito',
        'PASSWORD': 'MySQL14Sabrocit0',
        'HOST': 'sabrocito.mysql.pythonanywhere-services.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'/sabrosito-react/media')

#STATIC_URL = 'sabrosito-react/static/'

#STATICFILES_DIRS = (
 #   Path.joinpath(BASE_DIR, 'sabrosito-react/src'),
  #  Path.joinpath(BASE_DIR, 'sabrosito-react/Components/Paginas'),
#)
#STATIC_ROOT=os.path.join(BASE_DIR,'sabrosito-react/src')
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'sabrosito-react/src'),)
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'sabrosito-react/static'), os.path.join(BASE_DIR, 'c12-17-t-python/sabrosito-react/static'))
STATIC_DIR = os.path.join(BASE_DIR,'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = 'AddSession'

LOGIN_URL = 'login'

PAYPAL_TEST = True

PAYPAL_RECEIVER_EMAIL = 'sb-zycg615187836@business.example.com'